<?php

namespace AppBundle\Repository;

/**
 * ConstantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstantRepository extends \Doctrine\ORM\EntityRepository
{
}
