<?php

namespace AppBundle\Repository;

/**
 * StockRoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRoomRepository extends \Doctrine\ORM\EntityRepository
{
}
