# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin:
    resource: '@SyliusAdminBundle/Resources/config/routing.yml'
    prefix: /admin

sylius_api:
    resource: '@SyliusAdminApiBundle/Resources/config/routing.yml'
    prefix: /api

sylius_shop:
    resource: '@SyliusShopBundle/Resources/config/routing.yml'
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

sylius_shop_payum:
    resource: '@SyliusShopBundle/Resources/config/routing/payum.yml'

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

_liip_imagine:
    resource: '@LiipImagineBundle/Resources/config/routing.xml'

app_stock_room:
    resource: |
        alias: app.stockroom
        section: admin
        templates: SyliusAdminBundle:Crud
        redirect: update
        grid: app_admin_stockroom
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'search'
        permission: true
    prefix: /admin
    type: sylius.resource

#app_admin_stockroom_update:
#    defaults:
#        _controller: app.controller.stock:updateAction