# app/config/grids/grids.yml
imports:
    - { resource: 'admin/stockroom.yml' }
    - { resource: 'admin/constant.yml' }
    - { resource: 'admin/product.yml' }
    - { resource: 'admin/productstock.yml' }